language: python
python: 3.5

sudo: required
dist: trusty

branches:
  only:
    - master

env:
  - TOX_ENV=py27
  - TOX_ENV=py35

install:
- pip install tox
- pip install ijson

script:
    tox -e $TOX_ENV
