language: python
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cargo"
    - "target"

if: tag =~ ^v

install:
  - source .travis/install_cargo.sh

jobs:
  include:
    - &wheel
      stage: build wheel and send to github releases
      python: 3.7.9
      arch: arm64
      services:
        - docker
      env:
        - CIBW_BUILD: "'cp37-*'"
        - CIBW_SKIP: "'*-win32 *-manylinux_i686'"
        - CIBW_BEFORE_BUILD='source .travis/install_cargo.sh'
        - CIBW_ENVIRONMENT='PATH="$HOME/.cargo/bin:$PATH"'
      before_script:
        - python3 -m pip install cibuildwheel==1.7.1
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        token:
          secure: "FZmx00gL0m0uNVN8fpvqbUZSI20EEk4sgrEv4wpGFr8SFNwPb/VuizQRTapeF2AW9qzbfbUv4bR/+oSKu5jxvd+7+p9HlOZT285a5yfxay9OA8YUbpQz4a9J0CETOpxrA2wRRWBDqzjEWzLTGUquOhyBZn4cwujvA9syOdB7OSNKsB6ARc+zhqPeoMKc9JcjzwiEIh7tcCHoZ1epN5zyfsjqFEY8XlylHTU/WSI3SS9KIGuBqWf6/haoYD7BH+f2g56GMHvBEmGjk5cf/lrCpqiho7Z3fGgJcYf3fRWM3qSVUM9JyHUIqPS6oPZIp7zP40TztiK4Oeen4EpcS/KdoSdu5CjfgMYgF/qdlL28ntgnVYhcA/6IDSRg6V4H3b20qjsn3NlaNVdsSNCu3GzkvM/dtvp5I/41XcFCNqMOljMr3tRw2ZVo44/1vYW0FB0b0FjhjNcnMyTOQjSRR78zetdoorewTJdEmxthMieHIw1Mqzwg4e6JvsC30sh1uSaFq4FHrj2Fe6lAlgwPs1e9vx4w0Zs0kxxusNAdbBB8FH8paFuUEGjgT0Jo9KHOLtvRy+OU2OacQePuhG1kGBRvJz7O4/prAFLGWIW8tyZDnMCuv1vmk6YZd6ih3omkL178X94pjzavtlUip/ugF0NIwS5o+zucRow9txAX2jXgDCM="
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      arch: ppc64le

stages:
  - wheel
