language: python
os: linux
dist: xenial

cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.cargo"
    - "target"

if: |
  (type = push AND (branch = latest)) OR \
  (tag =~ ^v) OR \
  (type = pull_request)

script: tox -vv

install:
  - source .travis/install_cargo.sh

before_script: pip install tox-travis

jobs:
  include:
    - &test_ipfs
      name: integration (ipfs/redis)
      stage: test_ipfs
      python: 3.7.9
      before_install:
         - |-
            ### Copied from https://github.com/ipfs-shipyard/py-ipfs-http-client/blob/master/.travis.yml
            ### ==== MODIFY THIS WHEN CHANGING TARGET OR MINIMUM IPFS VERSION ==== ###
            case "${IPFS_VERSION:-latest}" in
               latest)  # Currently targeted version
                  VERSION=0.6.0
                  SHA512_LINUX=57e4ac078f4605e3e765c6c5a54fe6e7f45268fa7ec06fc54f03e0046643dff65718f6f143a67fe08c458a7c86e30b5a53c400bdb57b6a2122bdc5df1a4b8f33
                  SHA512_DARWIN=daf6fd4cef6b892ecff432895912c3962c4033d81c275fd8ab7172612f87db0aedfeb0d4c5a408a3f07d6f56399b4d5300d25e81c20d9cc9bed59fef02581360
                  SHA512_WINDOWS=2fb04eaa90b57fa9239a9e05234f288d017ba6d9001fa5330929faec3d6e0ad8b7d7eab35c3d0ee42fdd52e0d60a9b591dee3e59251b6d0e00c3d1ead15bf12d
               ;;
               compat)  # Earliest supported version
                  VERSION=0.4.22
                  SHA512_LINUX=49b99fec741d67f7bad8fb6fbbd984967f06dfc3de846d10dca34b166f621a182d12f13cf5ccf4e4f33747b67cede6f4205b4cd9b57ce5244128d1385ec82c85
               ;;
            esac
            ### ------------------------------ END ------------------------------- ###

            set -u

            # Derive usable parameters from the above constants
            case "${TRAVIS_OS_NAME}" in
               linux)
                  export IPFS_DL_PATH="go-ipfs/v${VERSION}/go-ipfs_v${VERSION}_linux-amd64.tar.gz"
                  export IPFS_DL_SHA512="${SHA512_LINUX}"
               ;;
               osx)
                  export IPFS_DL_PATH="go-ipfs/v${VERSION}/go-ipfs_v${VERSION}_darwin-amd64.tar.gz"
                  export IPFS_DL_SHA512="${SHA512_DARWIN}"
                  
                  # Make the `sha512sum` command available under that name
                  export PATH="$(echo /usr/local/Cellar/coreutils/*/libexec/gnubin):${PATH}"
               ;;
               windows)
                  export IPFS_DL_PATH="go-ipfs/v${VERSION}/go-ipfs_v${VERSION}_windows-amd64.zip"
                  export IPFS_DL_SHA512="${SHA512_WINDOWS}"
               ;;
            esac
            export IPFS_DL_BASENAME="${IPFS_DL_PATH##*/}"

            set +u
         # Download the daemon application
         - wget "https://dist.ipfs.io/${IPFS_DL_PATH}" 2>&1
         # Verify its checksum
         - echo "${IPFS_DL_SHA512}  ${IPFS_DL_BASENAME}" | sha512sum -c
         # Extract verified archive
         - |-
            if [[ "${IPFS_DL_BASENAME}" =~ .*\.zip ]];
            then
               unzip "${IPFS_DL_BASENAME}"
            else
               tar -xvf "${IPFS_DL_BASENAME}"
            fi
         # Add IPFS daemon to search path
         - export PATH="${PWD}/go-ipfs:${PATH}"
         - ipfs daemon --init --offline &>/dev/null &
      services:
        - redis
        - docker

    - &wheel
      stage: build wheel and send to github releases
      python: 3.7.9
      arch: arm64
      services:
        - docker
      env:
        - CIBW_BUILD: "'cp37-*'"
        - CIBW_SKIP: "'*-win32 *-manylinux_i686'"
        - CIBW_BEFORE_BUILD='source .travis/install_cargo.sh'
        - CIBW_ENVIRONMENT='PATH="$HOME/.cargo/bin:$PATH"'
      before_script:
        - python3 -m pip install cibuildwheel==1.7.1
      script:
        - python3 -m cibuildwheel --output-dir wheelhouse
      deploy:
        provider: releases
        token:
          secure: "FZmx00gL0m0uNVN8fpvqbUZSI20EEk4sgrEv4wpGFr8SFNwPb/VuizQRTapeF2AW9qzbfbUv4bR/+oSKu5jxvd+7+p9HlOZT285a5yfxay9OA8YUbpQz4a9J0CETOpxrA2wRRWBDqzjEWzLTGUquOhyBZn4cwujvA9syOdB7OSNKsB6ARc+zhqPeoMKc9JcjzwiEIh7tcCHoZ1epN5zyfsjqFEY8XlylHTU/WSI3SS9KIGuBqWf6/haoYD7BH+f2g56GMHvBEmGjk5cf/lrCpqiho7Z3fGgJcYf3fRWM3qSVUM9JyHUIqPS6oPZIp7zP40TztiK4Oeen4EpcS/KdoSdu5CjfgMYgF/qdlL28ntgnVYhcA/6IDSRg6V4H3b20qjsn3NlaNVdsSNCu3GzkvM/dtvp5I/41XcFCNqMOljMr3tRw2ZVo44/1vYW0FB0b0FjhjNcnMyTOQjSRR78zetdoorewTJdEmxthMieHIw1Mqzwg4e6JvsC30sh1uSaFq4FHrj2Fe6lAlgwPs1e9vx4w0Zs0kxxusNAdbBB8FH8paFuUEGjgT0Jo9KHOLtvRy+OU2OacQePuhG1kGBRvJz7O4/prAFLGWIW8tyZDnMCuv1vmk6YZd6ih3omkL178X94pjzavtlUip/ugF0NIwS5o+zucRow9txAX2jXgDCM="
        file_glob: true
        file: wheelhouse/sourmash*.whl
        skip_cleanup: true
        on:
          tags: true
    - <<: *wheel
      arch: ppc64le

stages:
  - test_ipfs
  - wheel
