name: "Dev env instructions"
on:
  pull_request:
    branches: [latest]
  push:
    branches: [latest]
jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-20.09

    - run: nix-shell --command "tox -e py39"

  mamba:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        fetch-depth: 0

    - name: cache conda
      uses: actions/cache@v1
      env:
        CACHE_NUMBER: 0
      with:
        path: ~/conda_pkgs_dir
        key:
          ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

    - name: setup conda
      uses: conda-incubator/setup-miniconda@e23d871804685e8c52189e5bd45e9145019f10af
      with:
        auto-update-conda: true
        python-version: 3.9
        channels: conda-forge,bioconda,defaults
        miniforge-variant: Mambaforge
        use-mamba: true
        activate-environment: sourmash_dev
        auto-activate-base: false
        use-only-tar-bz2: true

    - name: install dependencies
      run: mamba install tox-conda rust git compilers pandoc

    - name: run tests for 3.9
      run: tox -e py39
